package com.thundersoft.yj.service.cxf;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.0
 * 2017-10-11T17:38:34.822+08:00
 * Generated source version: 3.2.0
 * 
 */
@WebService(targetNamespace = "http://service.thundersoft.com/", name = "HelloWorldImpl")
@XmlSeeAlso({ObjectFactory.class})
public interface HelloWorldImpl {

    @WebMethod
    @RequestWrapper(localName = "updateImgName", targetNamespace = "http://service.thundersoft.com/", className = "com.thundersoft.yj.service.cxf.UpdateImgName")
    @ResponseWrapper(localName = "updateImgNameResponse", targetNamespace = "http://service.thundersoft.com/", className = "com.thundersoft.yj.service.cxf.UpdateImgNameResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String updateImgName(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    String arg2
    );
}
